#!/bin/bash
PATH=/usr/bin:/usr/sbin
HERE="$(dirname -- "$( readlink -f -- "$0"; )")"
FINISH_SLEEP="$(cat "$HERE/FINISH_SLEEP" 2>/dev/null || echo "")"
FINISH_REDIRECT="$(cat "$HERE/FINISH_REDIRECT" 2>/dev/null || echo "/dev/console")"

[ -n "$FINISH_REDIRECT" ] && exec &>"$FINISH_REDIRECT" || true

. /usr/lib/rc/functions

# Hacky hacky OpenRC compatibility
for script in /etc/local.d/*.stop; do
    [ -x "$script" ] && "$script"
done

run_shutdown
status "finished"
[ -n "$FINISH_SLEEP" ] && sleep "$FINISH_SLEEP" || true
