#!/bin/bash

PATH=/usr/bin:/usr/sbin

. /usr/lib/rc/functions

status "run_sysinit" run_sysinit

# Hacky hacky OpenRC compatibility
for script in /etc/local.d/*.start; do
    [ -x "$script" ] && status "running $script" "$script"
done

exec env - PATH=$PATH \

status "Initialization complete"
